### ISSUE TITLE
打开FileChooserActivity报错

### ISSUE THREAD

**Issue by lichao3140** [supertaohaili/FileChooser#2]
我用的是3288的板子，android5.1的 系统，运行报错
ava.lang.RuntimeException: Unable to start activity ComponentInfo{com.lichao.filechooser/com.thl.filechooser.FileChooserActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2345)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5288)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
        at java.io.File.fixSlashes(File.java:185)
        at java.io.File.<init>(File.java:134)
        at com.thl.filechooser.FileTourController.getSDcard0(FileTourController.java:113)
        at com.thl.filechooser.FileTourController.getRootFile(FileTourController.java:95)
        at com.thl.filechooser.FileTourController.<init>(FileTourController.java:33)
        at com.thl.filechooser.FileChooserActivity.initListener(FileChooserActivity.java:68)
        at com.thl.filechooser.FileChooserActivity.onCreate(FileChooserActivity.java:42)
        at android.app.Activity.performCreate(Activity.java:6222)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2407) 
        at android.app.ActivityThread.access$800(ActivityThread.java:151) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5288) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by lichao3140** [comment]
大神，可不可以帮忙解答下？谢谢

**Comment by smm113522** [comment]
AndroidManifest.xml 里面添加activity 就可以了。看demo 。。

**Comment by Auto-Tifou** [comment]
你好，请问下我也遇到你一样的bug报错，手机上都能用，但是高清屏部分就报这个错误，请问你最后是怎样解决的呢？

**Comment by Auto-Tifou** [comment]
> 大神，可不可以帮忙解答下？谢谢

大神，你好，能请问下你这个问题咋解决的吗，我在高亮屏遇到你一样的这个问题，其他设备都能用。
